# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Docker Commands

on:
  push:
    branches: [ 'TestDockerInGithubActionsX' ]

jobs:
  check_docker_changes:
    name: Find Docker-related changes
    outputs:
      found_one: ${{ steps.check_files.outputs.found_one }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "::set-output name=found_one::false"
          git diff --name-only HEAD^ HEAD > diff_files.txt
          while IFS= read -r file; do
            if [[ $file == *docker* ]]; then
              echo "::set-output name=found_one::true"
              break
            fi
          done < diff_files.txt

  build:
    runs-on: ubuntu-latest
    needs: check_docker_changes
    strategy:
      matrix:
        python-version: ['3.6'] #, '3.8']
    env:
      zoneId: xWbV4
      image_ctrl: "public.ecr.aws/neotys/neoload-controller:7.7.0"
      image_lg: "public.ecr.aws/neotys/neoload-loadgenerator:7.7.0"
      merge_to_trunk: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      integration_moment: ${{ github.event_name == 'pull_request' }}
      docker_files_changed: ${{ needs.check_docker_changes.outputs.found_one == 'true' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Echo Job State Variables
      run: |
        echo "merge_to_trunk: ${{ env.merge_to_trunk }}"
        echo "integration_moment: ${{ env.integration_moment }}"
        echo "docker_files_changed: ${{ env.docker_files_changed }}"
    - name: Pre-cache Docker Images
      if: ${{ env.merge_to_trunk || env.integration_moment || env.docker_files_changed }}
      run: |
        docker pull ${{ env.image_ctrl }}
        docker pull ${{ env.image_lg }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest (unit / mocks)
      run: |
        PYTHONPATH="neoload" COVERAGE_FILE=.coverage.unit coverage3 run -m pytest
    - name: Test with pytest (live calls / integration)
      if: ${{ env.merge_to_trunk || env.integration_moment || env.docker_files_changed }}
      run: |
        neoload config set docker.controller.image=${{ env.image_ctrl }}
        neoload config set docker.lg.image=${{ env.image_lg }}
        neoload config set docker.zone=${{ env.zoneId }}
        PYTHONPATH="neoload" COVERAGE_FILE=.coverage.live coverage3 run -m pytest -v -x -m "makelivecalls" --makelivecalls --token ${{ secrets.NLWEB_TOKEN }} --url ${{ secrets.NLWEB_API_URL }} --workspace CLI
    - name: Combine and Create Coverage Report
      run: |
        coverage3 combine
        coverage3 xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Zip Test Folder on failure
      if: failure()
      run: zip -r tests.zip tests/
    - name: Upload Test Folder on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-folder ${{ matrix.node-version }}
        path: tests.zip
        retention-days: 5
